export const portfolioItems = [
  {
    id: "1",
    tags: ["Leadership", "&", "Accessibility"],
    icon: "",
    iconUrl: "",
    title: "Public Accounts of Canada 2019 Web Conversion",
    desc: "Led the Public Accounts of Canada 2019 Web Conversion Process among all interns, mentoring 6 interns over a 4-month period. Ensured over 5000 public-facing pages met <strong>accessibility</strong>, bilingual, and web standards best practices at scale.",
    img: "/PA2019.png",
    url: "https://epe.lac-bac.gc.ca/100/201/301/comptes_publics_can/html/2019/recgen/cpc-pac/2019/index-eng.html",
    cta: "View Project",
  },
  {
    id: "2",
    tags: ["State Management"],
    icon: "",
    iconUrl: "",
    title: "JavaScript Blackjack",
    desc: "A Blackjack app built around maintaining complex <strong>game states</strong>, advanced player actions including split and double, betting logic, and side bet mechanics.",
    img: "/blackjack.png",
    url: "https://henry-blackjack.netlify.app/",
    cta: "Play Game",
  },
  {
    id: "3",
    tags: ["Backend App"],
    icon: "/GitHub-Mark-Light-32px.png",
    iconUrl: "https://github.com/henrygDev/merng-social-app",
    title: "Social Media App",
    desc: "A social media app built on the MERNG stack <strong>(MongoDB, Express, React, Node.JS, GraphQL)</strong> with the completed features of the database, server, login, registration, authentication <strong>(JWT)</strong>, post creation, post deletion, likes, and comments. Backend only.",
    img: "/merng.png",
    url: "",
    cta: "",
  },
  {
    id: "4",
    tags: ["React", "API"],
    icon: "/GitHub-Mark-Light-32px.png",
    iconUrl: "https://github.com/henrygDev/react-rmdb",
    title: "React Movie Database",
    desc: "Movie database based on <strong>React</strong>. Movie data was fetched through <strong>REST APIs</strong> from the The Movie Database and returned as <strong>JSON</strong> outputs.",
    img: "/react-rmdb.png",
    url: "",
    cta: "",
  },
];
